In [1]:
import numpy as np  # Importing numpy 'as' np is just to reduce typing...

In [2]:
np.arange(10, 3, -1)


array([10,  9,  8,  7,  6,  5,  4])

In [3]:
10/3

3

In [4]:
dtype

NameError: name 'dtype' is not defined

In [5]:
dtype = 10/3

In [6]:
print dtype

3


In [7]:
import time
time.ctime()

'Mon Sep 19 12:18:04 2016'

In [8]:
x = 16
x

16

In [9]:
np.sqrt(x)

4.0

In [10]:
x = np.arange(1, 7)

In [11]:
x

array([1, 2, 3, 4, 5, 6])

In [14]:
x = np.sqrt(x)

In [15]:
x

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974])

In [16]:
choices = np.arange(1, 10000)

In [17]:
np.random.choice(choices, 20, replace=False)

array([9146, 3553, 4253, 1605, 4190, 6226, 4331, 7469, 6857, 9479, 5620,
        971, 3897, 1898, 7638,  234, 9846, 9578, 7804, 3355])

In [18]:
np.random.choice(np.arange(1, 10000), 20, replace=False)

array([9195, 5337, 2000, 4980, 5855, 6660, 8340, 3844, 1928, 7210, 2537,
       6745, 4764, 4906, 2027, 9855, 5428, 6289, 5913, 2431])

In [19]:
5 ** 2

25

In [20]:
5.**2.

25.0

In [21]:
8 + 4 / 2

10

In [22]:
(8+4) / 2

6

In [23]:
3**2

9

In [24]:
np.sqrt(3.)

1.7320508075688772

In [25]:
8.**(1./3.)

2.0

In [26]:
np.exp(2)

7.3890560989306504

In [27]:
np.log(100)

4.6051701859880918

In [28]:
np.log10(100)

2.0

In [29]:
np.log2(100)

6.6438561897747244

In [30]:
np.cos(np.pi/2)

6.123233995736766e-17

In [31]:
np.sin(np.pi/2)

1.0

In [32]:
np.tan(np.pi/2)

16331239353195370.0

In [38]:
import math
np.cos(-1)

0.54030230586813977

In [39]:
np.sin(np.pi)

1.2246467991473532e-16

In [40]:
np.float64(1.) / 0

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in double_scalars
  if __name__ == '__main__':


inf

In [41]:
np.float64(0.) / 0.

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':


nan

In [42]:
np.sqrt(-9+0j)

3j

In [48]:
name = "python"

In [49]:
name

'python'

In [50]:
"name"

'name'

In [51]:
name = python

NameError: name 'python' is not defined

In [52]:
%config InlineBackend.figure_format = 'svg'
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns  # Makes for nicer plots
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 8, 4

In [53]:
l = [7, 'Heisenberg', 3.14, -1789710578, 'Happy Eating!']
s = pd.Series(l)
s

0                7
1       Heisenberg
2             3.14
3      -1789710578
4    Happy Eating!
dtype: object

In [54]:
s = pd.Series([7, 'Heisenberg', 3.14, -1789710578, 'Happy Eating!'],
              index=['A', 'Z', 'C', 'Y', 'E'])
s

A                7
Z       Heisenberg
C             3.14
Y      -1789710578
E    Happy Eating!
dtype: object

In [55]:
d = {'Chicago': 1000, 'New York': 1300, 'Portland': 900, 'San Francisco': 1100,
     'Austin': 450, 'Boston': None}
cities = pd.Series(d)
cities

Austin            450.0
Boston              NaN
Chicago          1000.0
New York         1300.0
Portland          900.0
San Francisco    1100.0
dtype: float64

In [56]:
cities.iloc[0]

450.0

In [57]:
print(type(cities['Chicago']))
names = ['Chicago', 'Portland', 'San Francisco']
cities[['Chicago', 'Portland', 'San Francisco']]

<type 'numpy.float64'>


Chicago          1000.0
Portland          900.0
San Francisco    1100.0
dtype: float64

In [58]:
cities[cities > 1000]

New York         1300.0
San Francisco    1100.0
dtype: float64

In [59]:
less_than_1000 = cities < 1000
print(less_than_1000)
print(cities[less_than_1000])

Austin            True
Boston           False
Chicago          False
New York         False
Portland          True
San Francisco    False
dtype: bool
Austin      450.0
Portland    900.0
dtype: float64


In [60]:
# Changing based on the index
print('Old value:', cities['Chicago'])
cities['Chicago'] = 1400
print('New value:', cities['Chicago'])

('Old value:', 1000.0)
('New value:', 1400.0)


In [61]:
print(cities[cities < 1000])
cities[cities < 1000] = 750

print(cities[cities < 1000])

Austin      450.0
Portland    900.0
dtype: float64
Austin      750.0
Portland    750.0
dtype: float64


In [62]:
print('Seattle' in cities)

False


In [63]:
print('San Francisco' in cities)

True


In [64]:
cities / 3

Austin           250.000000
Boston                  NaN
Chicago          466.666667
New York         433.333333
Portland         250.000000
San Francisco    366.666667
dtype: float64

In [65]:
cities

Austin            750.0
Boston              NaN
Chicago          1400.0
New York         1300.0
Portland          750.0
San Francisco    1100.0
dtype: float64

In [66]:
print(cities[['Chicago', 'New York', 'Portland']])

Chicago     1400.0
New York    1300.0
Portland     750.0
dtype: float64


In [67]:
print('\n')

In [68]:

print(cities[['Chicago', 'New York', 'Portland']])
print('\n')
print(cities[['Austin', 'New York']])
print('\n')
print(cities[['Chicago', 'New York', 'Portland']] + cities[['Austin', 'New York']])

Chicago     1400.0
New York    1300.0
Portland     750.0
dtype: float64


Austin       750.0
New York    1300.0
dtype: float64


Austin         NaN
Chicago        NaN
New York    2600.0
Portland       NaN
dtype: float64


In [69]:
cities.isnull()

Austin           False
Boston            True
Chicago          False
New York         False
Portland         False
San Francisco    False
dtype: bool

In [70]:
print(cities.isnull())

Austin           False
Boston            True
Chicago          False
New York         False
Portland         False
San Francisco    False
dtype: bool


In [71]:
print('\n')

In [72]:
print(cities[cities.isnull()])

Boston   NaN
dtype: float64


In [73]:

data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
        'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions', 'Lions', 'Lions'],
        'wins': [11, 8, 10, 15, 11, 6, 10, 4],
        'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data, columns=['year', 'team', 'wins', 'losses'])
football

year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12

In [76]:
from_csv = pd.read_csv('/Users/davidleifer/Desktop/space-time-analytics/swim100m.csv')

In [77]:
from_csv.head()

year  time sex
0  1905  65.8   M
1  1908  65.6   M
2  1910  62.8   M
3  1912  61.6   M
4  1918  61.4   M

In [78]:
cols = ["year", "mon", "day", "tmax", "tmin", "precip", "snow", "snowcover"]
no_headers = pd.read_csv("/Users/davidleifer/Desktop/space-time-analytics/boulderdaily.complete", sep='\s+', header=None,
                         names=cols, skiprows=1, skipfooter=14, engine='python',
                         na_values=["-998", "-998.00", "-999.00"])
no_headers.dropna().head()

year  mon  day  tmax  tmin  precip  snow  snowcover
18879  1948    8    1  89.0  58.0    0.01   0.0        0.0
18880  1948    8    2  90.0  56.0    0.01   0.0        0.0
18881  1948    8    3  77.0  57.0    0.02   0.0        0.0
18882  1948    8    4  67.0  57.0    0.12   0.0        0.0
18883  1948    8    5  79.0  57.0    0.04   0.0        0.0

In [79]:
import openpyxl

ImportError: No module named openpyxl

In [80]:
import openpyxl

In [81]:
football.head()

year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5

In [83]:
football.to_excel('/Users/davidleifer/Desktop/space-time-analytics/football.xlsx', index=False)

In [85]:
import glob
print(glob.glob("/Users/davidleifer/Desktop/space-time-analytics/*xlsx"))

['/Users/davidleifer/Desktop/space-time-analytics/football.xlsx']


In [86]:
del football

In [87]:
football = pd.read_excel('/Users/davidleifer/Desktop/space-time-analytics/football.xlsx', 'Sheet1')

In [101]:
football

year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12

In [104]:
import html5lib
import lxml